qm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:query_id>/trend/', views.trend, name='trend'),
    path('<int:query_id>/pq/<int:site>/', views.pq, name='pq'),
    path('events/<slug:endpointname>/<int:query_id>/<str:eventdate>/', views.events, name='events'),
    path('storyline/<str:storylineids>/<str:eventdate>/', views.storyline, name='storyline'),
    path('<int:query_id>/detail/', views.querydetail, name='querydetail'),
    path('debug', views.debug, name='debug'),
    path('timeline', views.timeline, name='timeline'),
    path('<int:query_id>/regen/', views.regen, name='regen'),
    path('<int:query_id>/progress/', views.progress, name='progress'),
    path('<int:query_id>/deletestats/', views.deletestats, name='deletestats'),
    path('netview', views.netview, name='netview'),
    path('about', views.about, name='about'),
    path('notifications', views.notifications, name='notifications'),
]

qm/models.py
from django.contrib.auth.models import User
from django.db import models
from simple_history.models import HistoricalRecords

class Country(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = "countries"

class MitreTactic(models.Model):
    mitre_id = models.CharField(max_length=15, unique=True)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    position = models.IntegerField(blank=False)
    
    def __str__(self):
        return '{} - {}'.format(self.mitre_id, self.name)
    
    class Meta:
        ordering = ['position']

class MitreTechnique(models.Model):
    mitre_id = models.CharField(max_length=15, unique=True)
    name = models.CharField(max_length=150)
    is_subtechnique = models.BooleanField() 
    mitre_technique = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    mitre_tactic = models.ManyToManyField(MitreTactic)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return '{} - {}'.format(self.mitre_id, self.name)
    
    class Meta:
        ordering = ['mitre_id']

class ThreatName(models.Model):
    name = models.CharField(max_length=100, verbose_name="Threat name or software", unique=True)
    aka_name = models.CharField(max_length=500, blank=True, help_text="Also known as, separator: comma")
    references = models.TextField(blank=True, help_text="List of sources, one per line")
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class ThreatActor(models.Model):
    name = models.CharField(max_length=100, verbose_name="Threat actor", unique=True)
    aka_name = models.CharField(max_length=500, blank=True, help_text="Also known as, separator: comma")
    source_country = models.ForeignKey(Country, blank=True, null=True, on_delete=models.CASCADE)
    references = models.TextField(blank=True, help_text="List of sources, one per line")
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class TargetOs(models.Model):
    name = models.CharField(max_length=10, unique=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "target OS"

class Vulnerability(models.Model):
    name = models.CharField(max_length=20, verbose_name="format: CVE-XXXX-XXXX", unique=True)
    base_score = models.FloatField()
    description = models.TextField(blank=True)
    references = models.TextField(blank=True, help_text="List of sources, one per line")
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = "vulnerabilities"

class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    short_name = models.CharField(max_length=4, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "categories"

class Query(models.Model):
    STATUS_CHOICES = [
        ('DRAFT', 'Draft'),
        ('DIST', 'Production'),
    ]
    CONFIDENCE_CHOICES = [
        (1, 'Low'),
        (2, 'Medium'),
        (3, 'High'),
        (4, 'Critical'),
    ]
    RELEVANCE_CHOICES = [
        (1, 'Low'),
        (2, 'Medium'),
        (3, 'High'),
        (4, 'Critical'),
    ]
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True, help_text="Description, Markdown syntax")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    notes = models.TextField(blank=True, help_text="Threat hunting notes, Markdown syntax")
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, editable=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    pub_status = models.CharField(max_length=5, choices=STATUS_CHOICES, default='DRAFT')
    confidence = models.IntegerField(choices=CONFIDENCE_CHOICES, default=1)
    relevance = models.IntegerField(choices=RELEVANCE_CHOICES, default=1)
    weighted_relevance = models.GeneratedField(
        expression=models.F("relevance") * models.F("confidence")/4,
        output_field=models.FloatField(),
        db_persist=False
    )
    query = models.TextField()
    columns = models.TextField(blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    mitre_techniques = models.ManyToManyField(MitreTechnique, blank=True)
    threats = models.ManyToManyField(ThreatName, blank=True)
    actors = models.ManyToManyField(ThreatActor, blank=True)
    target_os = models.ManyToManyField(TargetOs, blank=True)
    vulnerabilities = models.ManyToManyField(Vulnerability, blank=True)
    emulation_validation = models.TextField(blank=True, help_text="Emulation and validation, Markdown syntax")
    references = models.TextField(blank=True, help_text="List of sources, one per line")
    star_rule = models.BooleanField(default=False)
    run_daily = models.BooleanField(default=True)
    run_daily_lock = models.BooleanField(default=False, help_text="Prevents the run_daily flag from being unset and stats from being deleted automatically")
    dynamic_query = models.BooleanField(default=False)
    anomaly_threshold_count = models.IntegerField(default=2, help_text="Value range from 0 to 3. The higher the less sensitive")
    anomaly_threshold_endpoints = models.IntegerField(default=2, help_text="Value range from 0 to 3. The higher the less sensitive")
    maxhosts_count = models.IntegerField(default=0, help_text="Counts how many times max hosts threshold is reached")
    query_error = models.BooleanField(default=False, editable=False)
    query_error_message = models.TextField(blank=True, editable=False)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "queries"

    def has_changed(self):
        if not self.pk:
            return True  # New object, definitely changed (being created)
        
        try:
            old = Query.objects.get(pk=self.pk)
        except Query.DoesNotExist:
            return True  # New object

        for field in self._meta.fields:
            field_name = field.name
            if getattr(old, field_name) != getattr(self, field_name):
                return True  # At least one field changed
        return False  # No changes

    def save(self, *args, **kwargs):
        # To prevent simple-history from logging useless entries (when no change)
        # we only call save method if there is a real change
        if self.has_changed():
            super().save(*args, **kwargs)

class Campaign(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField(blank=True, null=True)
    nb_queries = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name
   
class Snapshot(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    query = models.ForeignKey(Query, on_delete=models.CASCADE)
    date = models.DateField()
    runtime = models.FloatField()
    hits_count = models.IntegerField(default=0)
    hits_endpoints = models.IntegerField(default=0)
    hits_c1 = models.IntegerField(default=0)
    hits_c2 = models.IntegerField(default=0)
    hits_c3 = models.IntegerField(default=0)
    zscore_count = models.FloatField(default=0)
    zscore_endpoints = models.FloatField(default=0)
    anomaly_alert_count = models.BooleanField(default=False)
    anomaly_alert_endpoints = models.BooleanField(default=False)
    
    def __str__(self):
        return '{} - {}'.format(self.date, self.query.name)

class Endpoint(models.Model):
    hostname = models.CharField(max_length=253)
    site = models.CharField(max_length=253, blank=True)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)
    storylineid = models.CharField(max_length=255, blank=True)
    
    def __str__(self):
        return '{} - {} - {}'.format(self.snapshot.date, self.hostname, self.snapshot.query.name)

class CeleryStatus(models.Model):
    query = models.ForeignKey(Query, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    progress = models.FloatField()

    def __str__(self):
        return self.query.name
    
    class Meta:
        verbose_name_plural = "celery status"

qm/templates/about.html
{% extends "base.html" %}

{% block body %}
<pre>
 _____  ______ ______ _____  _    _ _    _ _   _ _______ ______ _____  
|  __ \|  ____|  ____|  __ \| |  | | |  | | \ | |__   __|  ____|  __ \ 
| |  | | |__  | |__  | |__) | |__| | |  | |  \| |  | |  | |__  | |__) |
| |  | |  __| |  __| |  ___/|  __  | |  | | . ` |  | |  |  __| |  _  / 
| |__| | |____| |____| |    | |  | | |__| | |\  |  | |  | |____| | \ \ 
|_____/|______|______|_|    |_|  |_|\____/|_| \_|  |_|  |______|_|  \_\
                                                       Version: {{ version }}
</pre>
{% endblock %}

qm/templates/base.html
{% load qm_extras %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="/static/fontawesome/all.min.css" />
<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/base.css">
{% block style %}{% endblock %}
{{ redirect_to_login_immediately }}
</head>
<body>

<section>
    <div class="rt-container">
		<div class="col-rt-12">
			<div class="Scriptcontent">
				<div id="container">
					<nav>
						<ul>
							<li><a class="deephunter" href="#">DeepHunter<span class="blinking-cursor">_</span></a></li>

							<li><a class="{{ request.path|isactiveurl:"/" }}" href="/">Analytics</a></li>
							<li><a class="{{ request.path|isactiveurl:"/timeline" }}" href="/timeline">Timeline</a></li>
							<li><a class="{{ request.path|isactiveurl:"/netview" }}" href="/netview">Netview</a></li>

							<li><a href="#">Reports</a>
							<ul>
								<li><a class="{{ request.path|isactiveurl:"/reports/campaigns_stats" }}" href="/reports/campaigns_stats">Campaigns stats</a></li>
								<li><a class="{{ request.path|isactiveurl:"/reports/analytics_perfs" }}" href="/reports/analytics_perfs">Analytics perfs</a></li>
								<li><a class="{{ request.path|isactiveurl:"/reports/endpoints" }}" href="/reports/endpoints">Last campaign endpoints</a></li>
								<li><a class="{{ request.path|isactiveurl:"/reports/mitre" }}" href="/reports/mitre">Current MITRE coverage</a></li>
								<li><a class="{{ request.path|isactiveurl:"/reports/missing_mitre" }}" href="/reports/missing_mitre">Missing MITRE mapping</a></li>
								<li><a class="{{ request.path|isactiveurl:"/reports/disabled_analytics" }}" href="/reports/disabled_analytics">Auto-disabled Analytics</a></li>
								<li><a class="{{ request.path|isactiveurl:"/reports/query_error" }}" href="/reports/query_error">Analytics with errors</a></li>
							</ul>        
							</li>

							<li><a href="#">Tools</a>
							<ul>
								<li><a class="{{ request.path|isactiveurl:"/extensions/vthashchecker" }}" href="/extensions/vthashchecker">VirusTotal Hash Checker</a></li>
								<li><a class="{{ request.path|isactiveurl:"/extensions/vtipchecker" }}" href="/extensions/vtipchecker">VirusTotal IP Checker</a></li>
								<li><a class="{{ request.path|isactiveurl:"/extensions/malwarebazaarhashchecker" }}" href="/extensions/malwarebazaarhashchecker">MalwareBazaar Hash Check</a></li>

								<li><a class="{{ request.path|isactiveurl:"/extensions/loldriverhashchecker" }}" href="/extensions/loldriverhashchecker">LOL Driver Hash Checker</a></li>
								<li><a class="{{ request.path|isactiveurl:"/extensions/whois" }}" href="/extensions/whois">Whois</a></li>
							</ul>        
							</li>

							<li><a href="#">Admin</a>
							<ul>
								<li><a class="{{ request.path|isactiveurl:"/admin" }}" href="/admin">Backend</a></li>
								{% if request.user.is_superuser %}
									<li><a class="{{ request.path|isactiveurl:"/debug" }}" href="/debug">Debug</a></li>
								{% endif %}
							</ul> 
							</li>

							<li><a href="#">Help</a>
							<ul>
								<li><a target="_blank" href="https://deephunter.readthedocs.io/en/latest/">Documentation</a></li>
								<li><a class="{{ request.path|isactiveurl:"/about" }}" href="/about">About</a></li>
							</ul>
							</li>
							
							<li><a href="/logout">Log out</a></li>
							{% if messages %}<li><a href="/notifications"><i class="fa-solid fa-bell"></i></a></li>{% endif %}

						</ul>
					</nav>
				</div>
    		</div>
		</div>
    </div>
</section>

{% block body %}{% endblock %}
</body>
</html>

qm/templates/debug.html
{% extends "base.html" %}

{% block body %}
<pre>{{ debug }}</pre>
{% endblock %}

qm/templates/netview.html
{% extends "base.html" %}
{% load qm_extras %}

{% block style %}
<link rel="stylesheet" href="/static/css/stats.css" />
<script src="/static/jquery/jquery.min.js"></script>
{% endblock %}

{% block body %}
<h1>Network View</h1>
<form action="" method="get">
	{% csrf_token %}
	<label for="hostname">Endpoint</label>
	<input id="hostname" name="hostname" type="text" value="{{ hostname }}">
	<label for="storylineid">Storyline ID</label>
	<input id="storylineid" name="storylineid" type="text" value="{{ storylineid }}">
	<label for="timerange">Time range</label>
	<select id="timerange" name="timerange">
		<option value="24" {{ timerange|isselectedoption:"24" }}>Last 24h</option>
		<option value="36" {{ timerange|isselectedoption:"36" }}>Last 36h</option>
		<option value="48" {{ timerange|isselectedoption:"48" }}>Last 48h</option>
		<option value="72" {{ timerange|isselectedoption:"72" }}>Last 72h</option>
	</select>
	<input type="submit" />
</form>
<input type="checkbox" id="togglevis" checked />
<label for="togglevis">Hide private IP addresses</label>

<br />
<pre>{{ debug }}</pre>
{% if ips|length > 0 %}
	<p>Showing all IP addresses but localhost. VT score only shown for public IP addresses.</p>
	<table id="tableip">
		<tr>
			<th>Dest IP</th>
			<th>Priv/Publ</th>
			<th>Popularity*</th>
			<th>VT malicious</th>
			<th>VT suspicious</th>
			<th>Ports</th>
		</tr>
		{% for i in ips %}
		<tr{% if i.iptype == "PRIV" %} class="priv"{% endif %}>
			<td>{% if i.iptype == "PUBL" %}<a title="{{ i.vt.whois }}" href="https://www.virustotal.com/gui/ip-address/{{ i.dstip }}" target="_blank">{{ i.dstip }}</a>{% else %}{{ i.dstip }}{% endif %}</td>
			<td class="acenter">{{ i.iptype }}</td>
			<td class="aright">{{ i.freq }}</td>
			<td class="acenter">{{ i.vt.malicious }}</td>
			<td class="acenter">{{ i.vt.suspicious }}</td>
			<td class="w800">{{ i.dstports }}</td>
		</tr>
		{% endfor %}
	</table>
	(*) How many endpoints have also reached this destination IP in the same time range

<script type="text/javascript" nonce="hg45dkl6m4">
$('#tableip').find('tr.priv').hide();
$('#togglevis').on('click', function() {
    $('#tableip').find('tr.priv').toggle();
});
</script>
{% endif %}
{% endblock %}

qm/templates/notifications.html
{% extends "base.html" %}

{% block body %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

qm/templates/query_detail.html
{% load qm_extras %}
{% load markup_tags %}
<div class="m10">
	<a href="{{ q.id }}/pq/0/" target="_blank" class="button">Run in PQ (all users)</a>
	{% if c1 %}<a href="{{ q.id }}/pq/1/" target="_blank" class="button">Run in PQ ({{ c1 }})</a>{% endif %}
	{% if c2 %}<a href="{{ q.id }}/pq/2/" target="_blank" class="button">Run in PQ ({{ c2 }})</a>{% endif %}
	{% if c3 %}<a href="{{ q.id }}/pq/3/" target="_blank" class="button">Run in PQ ({{ c3 }})</a>{% endif %}
	<a href="{{ q.id }}/trend/" target="_blank" class="button">See trend</a>
	<a href="/admin/qm/query/{{ q.id }}/change/" target="_blank" class="button">Edit in admin</a></li>
	{% if perms.qm.delete_campaign %}
		<div id="progress_{{ q.id }}" class="progress">...</div>&nbsp;
		<div class="progress"><a href="{{ q.id }}/deletestats/" target="_blank" class="buttonred">Delete stats</a></div>
	{% endif %}
</div>

{% if endpoints %}
<div class="ml40">
	<b>Top 10 endpoints: </b>
	{% for endpoint in endpoints %}
		<a href="/timeline?hostname={{ endpoint }}" target="_blank">{{ endpoint }}</a> |
	{% endfor %}
	<a href="/admin/qm/endpoint/?snapshot__query__name={{ q.name }}" target="_blank">See all endpoints...</a>
</div>
{% endif %}

<div class="ml40">
	<b>Created by: </b>{% if q.created_by %}{{ q.created_by }}{% else %}-{% endif %}
	&nbsp;|&nbsp;<b>Created on: </b>{{ q.pub_date }}
	&nbsp;|&nbsp;<b>Last modified: </b>{{ q.update_date }}
	&nbsp;[<a href="/admin/qm/query/{{ q.id }}/history/" target="_blank">history</a>]
</div>
<div class="ml40">
	<b>Tags: </b>{% if q.tags %}{% for tag in q.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}
</div>

<h1>DESCRIPTION</h1>
{% if q.description %}<div class="description">{{ q.description|apply_markup:"markdown" }}</div>{% endif %}
<h1>THREAT HUNTING NOTES</h1>
{% if q.notes %}<div class="description">{{ q.notes|apply_markup:"markdown" }}</div>{% endif %}

<h1>POWERQUERY</h1>
{% if q.query_error %}<div class="{% if 'errors' in q.query_error_message %}errormsg{% else %}warningmsg{% endif %}">{{ q.query_error_message }}</div>{% endif %}
<div class="w1000 ml40{% if q.query_error %}{% if 'errors' in q.query_error_message %} errorquery{% else %} warningquery{% endif %}{% endif %}"><pre>{{ q.query }}{% if q.columns %}<br />{{ q.columns }}{% endif %}</pre></div>

<h1>THREAT COVERAGE</h1>
<ul>
	<li><b>Target OS: </b>
		{% for os in q.target_os.all %}
			<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><path d="{{ os.name|os2icon }}"/></svg>
		{% endfor %}
	</li>
	<li><b>Vulnerabilities: </b>
		<ul>
		{% for vulnerability in q.vulnerabilities.all %}
			<li><div class="floatleft" title="{{ vulnerability.description }}">{{ vulnerability.name }}</div>
			<div class="vuln cve_{{ vulnerability.base_score|cvecolor }}">{{ vulnerability.base_score }}</div>
			{% if vulnerability.references %}&nbsp;&nbsp;{% for link in vulnerability.references|links %} [<a href="{{ link }}" target="_blank">link</a>]{% endfor %}{% endif %}
			</li>
		{% endfor %}
		</ul>
	</li>
	<li><b>Associated Threat Actors: </b>
		<ul>
		{% for actor in q.actors.all %}
			<li>{{ actor.name }}{% if actor.aka_name %} ({{ actor.aka_name }}){% endif %} | Source country: {{ actor.source_country }}
			{% if actor.references %}{% for link in actor.references|links %} [<a href="{{ link }}" target="_blank">link</a>]{% endfor %}{% endif %}
			</li>
		{% endfor %}
		</ul>
	</li>
	<li><b>Associated Threats: </b>
		<ul>
		{% for threat in q.threats.all %}
			<li>{{ threat.name }}{% if threat.aka_name %} ({{ threat.aka_name }}){% endif %}
			{% if threat.references %}{% for link in threat.references|links %} [<a href="{{ link }}" target="_blank">link</a>]{% endfor %}{% endif %}
			</li>
		{% endfor %}
		</ul>
	</li>
</ul>

<h1>MITRE INFORMATION</h1>
	<table class="mitre ml40">
		<tr><th>Tactic</th><th>Technique</th><th>Sub-technique</th></tr>
			{% for t in q.mitre_techniques.all %}
				<tr>
					<td>
					{% for tac in t.mitre_tactic.all %}
						<div><a href="https://attack.mitre.org/tactics/{{ tac.mitre_id }}/" target="_blank" title="{{ tac.description }}">{{ tac.name }}</a></div>
					{% endfor %}
					</td>
				{% if t.is_subtechnique %}
					<td><a href="https://attack.mitre.org/techniques/{{ t.mitre_technique.mitre_id }}/" target="_blank" title="{{ t.mitre_technique.description }}">{{ t.mitre_technique }}</a></td>
					<td><a href="https://attack.mitre.org/techniques/{{ t.mitre_id|repl }}/" target="_blank" title="{{ t.description }}">{{ t }}</a></td>
				{% else %}
					<td><a href="https://attack.mitre.org/techniques/{{ t.mitre_id }}/" target="_blank" title="{{ t.description }}">{{ t }}</a></td>
					<td>-</td>
				{% endif %}
				</tr>
			{% endfor %}
	</table>

<h1>EMULATION & VALIDATION</h1>
{% if q.emulation_validation %}<div class="description">{{ q.emulation_validation|apply_markup:"markdown" }}</div>{% endif %}

<h1>REFERENCES</h1>
{% if q.references %}<ul>{% for link in q.references|links %}<li><a href="{{ link }}" target="_blank">{{ link }}</a></li>{% endfor %}</ul>{% endif %}

{% if perms.qm.delete_campaign %}
<script type="text/javascript" nonce="jg6kl5z3v2">
$(document).ready(function() {
	setInterval(function() {
		$("#progress_{{ q.id }}").load('{{ q.id }}/progress/')
	}, 2000);
});
</script>
{% endif %}